import React from 'react'

function TermsAndConditions() {
  return (
     <div className='max-w-4xl mx-auto px-4 py-12 text-gray-700 dark:text-gray-400 leading-relaxed dark:[&_h1]:text-gray-200 [&_h1]:text-2xl [&_h1]:sm:text-3xl [&_h1]:font-bold [&_h1]:text-black [&_h1]:mb-6 dark:[&_h2]:text-gray-300 [&_h2]:text-xl [&_h2]:sm:text-2xl [&_h2]:font-semibold [&_h2]:text-black [&_h2]:mt-8 [&_h2]:mb-4 dark:[&_h3]:text-gray-300 [&_h3]:text-lg [&_h3]:sm:text-xl [&_h3]:font-semibold [&_h3]:text-black [&_h3]:mt-6 [&_h3]:mb-3 [&_h4]:text-base dark:[&_h4]:text-gray-300 [&_h4]:sm:text-lg [&_h4]:font-medium [&_h4]:text-black [&_h4]:mt-4 [&_h4]:mb-2 [&_p]:mb-4 [&_ul]:list-disc [&_ul]:pl-6 [&_ul]:mb-4 [&_li]:mb-2 [&_a]:text-indigo-600 dark:[&_a]:text-gray-300 [&_a]:hover:underline [&_strong]:text-black dark:[&_strong]:text-gray-300'>
      <h1>Terms and Conditions</h1>
      <p>Last updated: May 11, 2026</p>

      <h2>1. Acceptance of Terms</h2>
      <p>By accessing or using Vella, you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the service.</p>

      <h2>2. User Content</h2>
      <p>You retain full ownership of the blog posts and content you create on Vella. By posting content, you grant Vella a non-exclusive license to display it on the platform. You are solely responsible for ensuring your content does not violate any laws or third-party rights.</p>

      <h2>3. Prohibited Content</h2>
      <p>You agree not to post content that is spam, hateful, discriminatory, illegal, or violates the rights of others. One account per person is permitted.</p>

      <h2>4. Our Rights</h2>
      <p>Vella reserves the right to remove any content that violates these terms and to suspend or terminate accounts that abuse the platform, at our sole discretion.</p>

      <h2>5. AI-Generated Content</h2>
      <p>Vella provides an AI writing assistant powered by Google Gemini. Any content generated by AI is your responsibility. Vella does not guarantee the accuracy, quality, or appropriateness of AI-generated content.</p>

      <h2>6. Service</h2>
      <p>Vella is provided as-is. We may modify, suspend, or discontinue any feature at any time without notice. We do not guarantee uninterrupted availability of the service.</p>

      <h2>7. Limitation of Liability</h2>
      <p>Vella is not responsible for user-generated content posted on the platform. We are not liable for any data loss, service interruptions, or damages arising from your use of Vella.</p>

      <h2>8. Contact</h2>
      <p>For questions about these Terms, contact us at: <a href='mailto:ambersingh365@gmail.com'>ambersingh365@gmail.com</a></p>
    </div>
  )
}

export default TermsAndConditions
